import { cn } from '@/utils/cn'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NavbarDemo } from '@/components/navigation-menu'
import { MetaMaskProvider } from '@/providers/metamask-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <MetaMaskProvider>
        <body className={cn(inter.className, "")}>
          <NavbarDemo />
          {children}
        </body>
      </MetaMaskProvider>
    </html>

  )
}
